### ISSUE TITLE
Help with Interactive Debugging - AttributeError: '_ContainerApp' object has no attribute '_is_interactivity_enabled'

### ISSUE THREAD

**Issue by DrChrisLevy** [modal-labs/modal-client#1639] opened 2024-04-01 15:10 UTC
I am new to modal so the issue may just be that. I'm trying to jump into an Ipython shell as explained in the docs [here](https://modal.com/docs/guide/developing-debugging#interactive-functions). I have created a simple example that replicates the issue I am coming up against.

hello_world.py

```python
import modal


stub = modal.Stub("example-get-started")


@stub.function()
def f(name):
    print(f"HELLO WORLD {name}")
    modal.interact()
    import IPython

    IPython.embed()


@stub.local_entrypoint()
def main():
    f.remote('Chris')

```

```
modal run --interactive hello_world.py
```

<img width="1094" alt="Screenshot 2024-04-01 at 12 08 51 PM" src="https://github.com/modal-labs/modal-client/assets/16509365/d4e8fe01-125e-48c5-8f3b-4c7bfd5205a1">

**Comment by mwaskom** [comment] 2024-04-01 15:53
Hi, thanks for reporting and sorry about that. This was a regression on our end caused by some incomplete refactoring. I've just merged a fix, which should be live on PyPI in ≈10 minutes.

**Closed** 2024-04-01 15:52 UTC

**Comment by DrChrisLevy** [comment] 2024-04-02 00:30
Beautiful! Just tried it in the updated version and it worked. What an awesome feature. And thanks for the quick fix!

**Comment by kavins14** [comment] 2024-04-06 20:22
I'm using v0.62.42 and I'm still running into this issue. Here's my code:

<img width="531" alt="Screen Shot 2024-04-07 at 3 22 11 AM" src="https://github.com/modal-labs/modal-client/assets/18351436/38a3f6ed-2a97-49a6-912b-25b127057706">

Logs:

<img width="728" alt="Screen Shot 2024-04-07 at 3 21 38 AM" src="https://github.com/modal-labs/modal-client/assets/18351436/31b6ad5a-58da-470b-b147-6e0be70b1f9b">
