### ISSUE TITLE
Re-Deploy Fails

### ISSUE THREAD

**Issue by austrian-code-wizard** [modal-labs/modal-client#1353] opened 2024-02-14 20:26 UTC
## Description
I have a modal app (connected to this Github account) that I deployed yesterday. Today, I tried to re-deploy after making minor changes to one of the endpoints. I got the error message below. My local modal client is version 0.57.43.

## Resolution
I had to manually stop the deployed app and then deploy the app again. It's an easy fix, but wanted to open this issue as a heads up that there might be some problem when re-deploying an existing app.

## Error
<img width="1213" alt="image" src="https://github.com/modal-labs/modal-client/assets/23276233/69bec94e-afd5-43a4-8aa8-51819fc38d58">

**Comment by luiscape** [comment] 2024-02-14 21:15
Hi @austrian-code-wizard, sorry for the issue. We introduced a backend bug that caused this issue.

The issue is now fixed. Can you try again?

**Closed by luiscape** 2024-02-14 21:15 UTC
