### ISSUE TITLE
Support for Pydantic V1 vs V2

### ISSUE THREAD

**Issue by jxnl** [modal-labs/modal-client#1052] opened 2023-11-13 18:57 UTC
# Issue

I encountered difficulties while trying to support pydantic v2 because it is not compatible with v1.

![errors](https://pbs.twimg.com/media/F-0soqEaQAAB9uk?format=jpg&name=medium)

# Solution
To resolve this, you need to update fastapi to version `0.104.1` or newer. By doing so, you should be able to use pydantic v2 seamlessly within Modal.

**Comment by erikbern** [comment] 2023-11-13 19:37
This would probably break users of pydantic v1 though. We might have to just vendor the pydantic dependency, unfortunately

**Comment by harimohanraj** [comment] 2023-11-28 18:05
For what it's worth, I've also encountered issues with this and while it's not a blocker, would love to see a solution so I can take advantage of some of the features in Pydantic V2!

**Comment by fcakyon** [comment] 2023-12-30 09:12
Are there any updates @erikbern, does modal currently support pydantic v2?

Thanks for all the great work!

**Comment by mwaskom** [comment] 2024-01-12 15:37
@fcakyon we're working on a broader fix for this, but in the mean time you should be able to use Pydantic 2 so long as you also specify a recent version of `fastapi` in the `pip_install` step when you setup your image, e.g.

```python
image = Image.debian_slim().pip_install("pydantic>==2.5.3", "fastapi==0.109.0")
```

Let me know if you run into any issues with that, and hopefully we'll have this gotcha eliminated soon!

**Comment by rabernat** [comment] 2024-03-22 19:35
I have hit a similar issue. I need to install a [package](https://pypi.org/project/arraylake/) that depends on pydantic>2 in a modal image. 

I found that the `Image.debian_slim().pip_install("pydantic==2.5.3", "fastapi==0.109.0")` workaround above does work.

However, the catch is that I need to use conda / mamba to create my environment. Unfortunately the same workaround doesn't work with conda / mamba. Here's a minimal reproducer.

```python
from modal import Image, Stub

stub = Stub("pydantic-test")

pydantic_image = (
    Image.micromamba()
    .micromamba_install("pydantic==2.5.3", "fastapi==0.109.0", channels=["conda-forge"])
)

@stub.function(image=pydantic_image)
def sample():
    import pydantic
    print("pydantic.__version__", pydantic.__version__)


@stub.local_entrypoint()
def main():
    print(sample.remote())
```

This prints `pydantic.__version__ 1.10.10`.

**Comment by mwaskom** [comment] 2024-03-22 19:57
Ah I think the issue here is that you need to use `micromamba update` explicitly if you want different versions of a package you already have? Maybe we should add an `update: bool` flag do `Image.micromamba_install` 🤔 

In the meantime, even if you're using the `micromamba` base, you may be able to use `pip_install` to update pydantic/fastapi before `micromamba`-installing the dependency of interest? Yeah, mixing mamba and pip is not terrific environment hygiene, but that's already happening anyway since we instal the modal dependencies in the base image using `pip` either way.

**Comment by rabernat** [comment] 2024-03-22 20:15
Thanks for the help!

> I think the issue here is that you need to use `micromamba update` explicitly if you want different versions of a package you already have?

AFAIK specifying a specific package version with mamba / conda triggers that exact version to be installed. You can see this in the logs (here created with `force_build=True`)

<details>

```
Building image im-rhKzeTP7eL1gxexu76Sl52

=> Step 0: FROM base

=> Step 1: RUN micromamba install pydantic==2.5.3 fastapi==0.109.0 -c conda-forge --yes

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /opt/conda

  Updating specs:

   - pydantic==2.5.3
   - fastapi==0.109.0


  Package              Version  Build           Channel                   Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  + annotated-types      0.6.0  pyhd8ed1ab_0    conda-forge/noarch        17kB
  + anyio                3.7.1  pyhd8ed1ab_0    conda-forge/noarch        97kB
  + exceptiongroup       1.2.0  pyhd8ed1ab_2    conda-forge/noarch        21kB
  + fastapi            0.109.0  pyhd8ed1ab_0    conda-forge/noarch        71kB
  + idna                   3.6  pyhd8ed1ab_0    conda-forge/noarch        50kB
  + pydantic             2.5.3  pyhd8ed1ab_0    conda-forge/noarch       262kB
  + pydantic-core       2.14.6  py39h9fdd4d6_1  conda-forge/linux-64       2MB
  + python_abi             3.9  4_cp39          conda-forge/linux-64       6kB
  + sniffio              1.3.1  pyhd8ed1ab_0    conda-forge/noarch        15kB
  + starlette           0.35.0  pyhd8ed1ab_0    conda-forge/noarch        58kB
  + typing-extensions   4.10.0  hd8ed1ab_0      conda-forge/noarch        10kB
  + typing_extensions   4.10.0  pyha770c72_0    conda-forge/noarch        37kB

  Summary:

  Install: 12 packages

  Total download: 2MB

────────────────────────────────────────────────────────────────────────────────



Transaction starting
Linking typing_extensions-4.10.0-pyha770c72_0
warning  libmamba [typing_extensions-4.10.0-pyha770c72_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/typing_extensions.py
Linking idna-3.6-pyhd8ed1ab_0
warning  libmamba [idna-3.6-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/idna/__init__.py
    - lib/python3.9/site-packages/idna/codec.py
    - lib/python3.9/site-packages/idna/compat.py
    - lib/python3.9/site-packages/idna/core.py
    - lib/python3.9/site-packages/idna/idnadata.py
    - lib/python3.9/site-packages/idna/intranges.py
    - lib/python3.9/site-packages/idna/package_data.py
    - lib/python3.9/site-packages/idna/py.typed
    - lib/python3.9/site-packages/idna/uts46data.py
Linking sniffio-1.3.1-pyhd8ed1ab_0
warning  libmamba [sniffio-1.3.1-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/sniffio/__init__.py
    - lib/python3.9/site-packages/sniffio/_impl.py
    - lib/python3.9/site-packages/sniffio/_tests/__init__.py
    - lib/python3.9/site-packages/sniffio/_tests/test_sniffio.py
    - lib/python3.9/site-packages/sniffio/_version.py
    - lib/python3.9/site-packages/sniffio/py.typed
Linking exceptiongroup-1.2.0-pyhd8ed1ab_2
warning  libmamba [exceptiongroup-1.2.0-pyhd8ed1ab_2] The following files were already present in the environment:
    - lib/python3.9/site-packages/exceptiongroup/__init__.py
    - lib/python3.9/site-packages/exceptiongroup/_catch.py
    - lib/python3.9/site-packages/exceptiongroup/_exceptions.py
    - lib/python3.9/site-packages/exceptiongroup/_formatting.py
    - lib/python3.9/site-packages/exceptiongroup/_version.py
    - lib/python3.9/site-packages/exceptiongroup/py.typed
Linking typing-extensions-4.10.0-hd8ed1ab_0
Linking anyio-3.7.1-pyhd8ed1ab_0
warning  libmamba [anyio-3.7.1-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/anyio/__init__.py
    - lib/python3.9/site-packages/anyio/_backends/__init__.py
    - lib/python3.9/site-packages/anyio/_backends/_asyncio.py
    - lib/python3.9/site-packages/anyio/_backends/_trio.py
    - lib/python3.9/site-packages/anyio/_core/__init__.py
    - lib/python3.9/site-packages/anyio/_core/_compat.py
    - lib/python3.9/site-packages/anyio/_core/_eventloop.py
    - lib/python3.9/site-packages/anyio/_core/_exceptions.py
    - lib/python3.9/site-packages/anyio/_core/_fileio.py
    - lib/python3.9/site-packages/anyio/_core/_resources.py
    - lib/python3.9/site-packages/anyio/_core/_signals.py
    - lib/python3.9/site-packages/anyio/_core/_sockets.py
    - lib/python3.9/site-packages/anyio/_core/_streams.py
    - lib/python3.9/site-packages/anyio/_core/_subprocesses.py
    - lib/python3.9/site-packages/anyio/_core/_synchronization.py
    - lib/python3.9/site-packages/anyio/_core/_tasks.py
    - lib/python3.9/site-packages/anyio/_core/_testing.py
    - lib/python3.9/site-packages/anyio/_core/_typedattr.py
    - lib/python3.9/site-packages/anyio/abc/__init__.py
    - lib/python3.9/site-packages/anyio/abc/_resources.py
    - lib/python3.9/site-packages/anyio/abc/_sockets.py
    - lib/python3.9/site-packages/anyio/abc/_streams.py
    - lib/python3.9/site-packages/anyio/abc/_subprocesses.py
    - lib/python3.9/site-packages/anyio/abc/_tasks.py
    - lib/python3.9/site-packages/anyio/abc/_testing.py
    - lib/python3.9/site-packages/anyio/from_thread.py
    - lib/python3.9/site-packages/anyio/lowlevel.py
    - lib/python3.9/site-packages/anyio/py.typed
    - lib/python3.9/site-packages/anyio/pytest_plugin.py
    - lib/python3.9/site-packages/anyio/streams/__init__.py
    - lib/python3.9/site-packages/anyio/streams/buffered.py
    - lib/python3.9/site-packages/anyio/streams/file.py
    - lib/python3.9/site-packages/anyio/streams/memory.py
    - lib/python3.9/site-packages/anyio/streams/stapled.py
    - lib/python3.9/site-packages/anyio/streams/text.py
    - lib/python3.9/site-packages/anyio/streams/tls.py
    - lib/python3.9/site-packages/anyio/to_process.py
    - lib/python3.9/site-packages/anyio/to_thread.py
Linking annotated-types-0.6.0-pyhd8ed1ab_0
Linking starlette-0.35.0-pyhd8ed1ab_0
warning  libmamba [starlette-0.35.0-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/starlette/__init__.py
    - lib/python3.9/site-packages/starlette/_compat.py
    - lib/python3.9/site-packages/starlette/_utils.py
    - lib/python3.9/site-packages/starlette/applications.py
    - lib/python3.9/site-packages/starlette/authentication.py
    - lib/python3.9/site-packages/starlette/background.py
    - lib/python3.9/site-packages/starlette/concurrency.py
    - lib/python3.9/site-packages/starlette/config.py
    - lib/python3.9/site-packages/starlette/convertors.py
    - lib/python3.9/site-packages/starlette/datastructures.py
    - lib/python3.9/site-packages/starlette/endpoints.py
    - lib/python3.9/site-packages/starlette/exceptions.py
    - lib/python3.9/site-packages/starlette/formparsers.py
    - lib/python3.9/site-packages/starlette/middleware/__init__.py
    - lib/python3.9/site-packages/starlette/middleware/authentication.py
    - lib/python3.9/site-packages/starlette/middleware/base.py
    - lib/python3.9/site-packages/starlette/middleware/cors.py
    - lib/python3.9/site-packages/starlette/middleware/errors.py
    - lib/python3.9/site-packages/starlette/middleware/exceptions.py
    - lib/python3.9/site-packages/starlette/middleware/gzip.py
    - lib/python3.9/site-packages/starlette/middleware/httpsredirect.py
    - lib/python3.9/site-packages/starlette/middleware/sessions.py
    - lib/python3.9/site-packages/starlette/middleware/trustedhost.py
    - lib/python3.9/site-packages/starlette/middleware/wsgi.py
    - lib/python3.9/site-packages/starlette/py.typed
    - lib/python3.9/site-packages/starlette/requests.py
    - lib/python3.9/site-packages/starlette/responses.py
    - lib/python3.9/site-packages/starlette/routing.py
    - lib/python3.9/site-packages/starlette/schemas.py
    - lib/python3.9/site-packages/starlette/staticfiles.py
    - lib/python3.9/site-packages/starlette/status.py
    - lib/python3.9/site-packages/starlette/templating.py
    - lib/python3.9/site-packages/starlette/testclient.py
    - lib/python3.9/site-packages/starlette/types.py
    - lib/python3.9/site-packages/starlette/websockets.py
Linking python_abi-3.9-4_cp39
Linking pydantic-core-2.14.6-py39h9fdd4d6_1
Linking pydantic-2.5.3-pyhd8ed1ab_0
warning  libmamba [pydantic-2.5.3-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/pydantic/__init__.py
    - lib/python3.9/site-packages/pydantic/class_validators.py
    - lib/python3.9/site-packages/pydantic/color.py
    - lib/python3.9/site-packages/pydantic/config.py
    - lib/python3.9/site-packages/pydantic/dataclasses.py
    - lib/python3.9/site-packages/pydantic/datetime_parse.py
    - lib/python3.9/site-packages/pydantic/decorator.py
    - lib/python3.9/site-packages/pydantic/env_settings.py
    - lib/python3.9/site-packages/pydantic/error_wrappers.py
    - lib/python3.9/site-packages/pydantic/errors.py
    - lib/python3.9/site-packages/pydantic/fields.py
    - lib/python3.9/site-packages/pydantic/generics.py
    - lib/python3.9/site-packages/pydantic/json.py
    - lib/python3.9/site-packages/pydantic/main.py
    - lib/python3.9/site-packages/pydantic/mypy.py
    - lib/python3.9/site-packages/pydantic/networks.py
    - lib/python3.9/site-packages/pydantic/parse.py
    - lib/python3.9/site-packages/pydantic/py.typed
    - lib/python3.9/site-packages/pydantic/schema.py
    - lib/python3.9/site-packages/pydantic/tools.py
    - lib/python3.9/site-packages/pydantic/types.py
    - lib/python3.9/site-packages/pydantic/typing.py
    - lib/python3.9/site-packages/pydantic/utils.py
    - lib/python3.9/site-packages/pydantic/validators.py
    - lib/python3.9/site-packages/pydantic/version.py
Linking fastapi-0.109.0-pyhd8ed1ab_0
warning  libmamba [fastapi-0.109.0-pyhd8ed1ab_0] The following files were already present in the environment:
    - lib/python3.9/site-packages/fastapi/__init__.py
    - lib/python3.9/site-packages/fastapi/applications.py
    - lib/python3.9/site-packages/fastapi/background.py
    - lib/python3.9/site-packages/fastapi/concurrency.py
    - lib/python3.9/site-packages/fastapi/datastructures.py
    - lib/python3.9/site-packages/fastapi/dependencies/__init__.py
    - lib/python3.9/site-packages/fastapi/dependencies/models.py
    - lib/python3.9/site-packages/fastapi/dependencies/utils.py
    - lib/python3.9/site-packages/fastapi/encoders.py
    - lib/python3.9/site-packages/fastapi/exception_handlers.py
    - lib/python3.9/site-packages/fastapi/exceptions.py
    - lib/python3.9/site-packages/fastapi/logger.py
    - lib/python3.9/site-packages/fastapi/middleware/__init__.py
    - lib/python3.9/site-packages/fastapi/middleware/cors.py
    - lib/python3.9/site-packages/fastapi/middleware/gzip.py
    - lib/python3.9/site-packages/fastapi/middleware/httpsredirect.py
    - lib/python3.9/site-packages/fastapi/middleware/trustedhost.py
    - lib/python3.9/site-packages/fastapi/middleware/wsgi.py
    - lib/python3.9/site-packages/fastapi/openapi/__init__.py
    - lib/python3.9/site-packages/fastapi/openapi/constants.py
    - lib/python3.9/site-packages/fastapi/openapi/docs.py
    - lib/python3.9/site-packages/fastapi/openapi/models.py
    - lib/python3.9/site-packages/fastapi/openapi/utils.py
    - lib/python3.9/site-packages/fastapi/param_functions.py
    - lib/python3.9/site-packages/fastapi/params.py
    - lib/python3.9/site-packages/fastapi/py.typed
    - lib/python3.9/site-packages/fastapi/requests.py
    - lib/python3.9/site-packages/fastapi/responses.py
    - lib/python3.9/site-packages/fastapi/routing.py
    - lib/python3.9/site-packages/fastapi/security/__init__.py
    - lib/python3.9/site-packages/fastapi/security/api_key.py
    - lib/python3.9/site-packages/fastapi/security/base.py
    - lib/python3.9/site-packages/fastapi/security/http.py
    - lib/python3.9/site-packages/fastapi/security/oauth2.py
    - lib/python3.9/site-packages/fastapi/security/open_id_connect_url.py
    - lib/python3.9/site-packages/fastapi/security/utils.py
    - lib/python3.9/site-packages/fastapi/staticfiles.py
    - lib/python3.9/site-packages/fastapi/templating.py
    - lib/python3.9/site-packages/fastapi/testclient.py
    - lib/python3.9/site-packages/fastapi/types.py
    - lib/python3.9/site-packages/fastapi/utils.py
    - lib/python3.9/site-packages/fastapi/websockets.py
Transaction finished
Creating image snapshot...
Finished snapshot; took 1.80s

Built image im-rhKzeTP7eL1gxexu76Sl52 in 24.78s
✓ Created objects.
├── 🔨 Created mount /Users/rabernat/gh/earth-mover/serverless-sentinel/demo.py
└── 🔨 Created sample.
None
pydantic.__version__ 1.10.10
Stopping app - local entrypoint completed.
✓ App completed. View run at https://modal.com/earth-mover/apps/ap-ibbpDWMJszD7SzmqCfMNS5
```

</details>

The specified package versions are being installed by mamba according to the logs, but somehow not getting used. Adding a `print("pydantic", pydantic)` to the function shows `pydantic <module 'pydantic' from '/opt/conda/lib/python3.9/site-packages/pydantic/__init__.cpython-39-x86_64-linux-gnu.so'>`.


> you may be able to use `pip_install` to update pydantic/fastapi before `micromamba`-installing the dependency of interest?


The following did the trick...although I had to call pip _after_ mamba

```python
pydantic_image = (
    Image.micromamba()
    .micromamba_install(
        "arraylake",  # <-- the package with a pydantic 2 dependency
        channels=["conda-forge"],
    )
    .pip_install("pydantic==2.5.3", "fastapi==0.109.0")
)
```

**Comment by mwaskom** [comment] 2024-03-22 20:20
Hm, yeah I couldn't really interpret that log output. Are you being warned that the existing files are going to be overridden? Or that the install will have no effect because they are already there? Either way, glad you got it working.

**Comment by mwaskom** [comment] 2024-04-30 17:46
As of today our recommended solution here is to use the `2024.04` version of our image builder (i.e. `MODAL_IMAGE_BUILDER_VERSION=2024.04`) which will install fastapi 0.110.0 and pydantic `2.6.4` in the base image layer.

**Closed by mwaskom** 2024-04-30 17:46 UTC

**Comment by skunkwerk** [comment] 2024-07-21 06:56
how do you specify the modal image builder version?  is that an env var in my dockerfile?
